module.exports = Object.freeze({
  ROOT: "ROOT",
  SPLASH: "SPLASH",
  LOGIN: "LOGIN",
  HOME: "HOME",
  FAVOURITE: "FAVOURITE",
  MESSAGE: "MESSAGE",
  PROFILE: "PROFILE",
  SEARCH: "SEARCH",
  SPLASH: "SPLASH",
  UPLOAD: "UPLOAD",
  TAB_MAIN: "TAB_MAIN"
});
