# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'InstaSocial' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for InstaSocial
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/yoga.podspec'
  pod 'React', :path => '../node_modules/react-native',:subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
  ]
  # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'


  target 'InstaSocial-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InstaSocialTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'InstaSocial-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for InstaSocial-tvOS

end
